# Site settings
title: Kent Safranski
email: kent@fluidbyte.net
url: https://fluidbyte.github.io
description: "Web and Software Architect, Developer, and Designer from Onalaska, Wisconsin"
skills: "Architecture - Engineering - Leadership"
meta_author: Safranski Kent
tagline: "Web Software Design + Development, La Crosse / Onalaska Wisconsin"

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: fluidbyte

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 415579 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Kent Safranski
  location: Location
  social: Around the Web
  contact: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kentsafranski
  - title: github
    url: http://github.com/fluidbyte
  - title: stack-overflow
    url: http://stackoverflow.com/users/957500/fluidbyte

# Postal address (add as many lines as necessary)
address:
  - line: Onalaska, WI

# Credits content
contact: 
  - icon: envelope
    url: mailto:kent@fluidbyte.net
    text: kent@fluidbyte.net
  - icon: phone-square
    url: tel:6087979651
    text: 608.797.9651

# Build settings
markdown: kramdown
permalink: pretty
